Make it possible to start browser tests: Upgrade to Guava 13.0.1
For some reason, when staring the server as part of the Selenium tests,
I need to use Google Guava 13 not 10, or there's this error:
  java.lang.NoSuchMethodError:
    com.google.common.cache.CacheBuilder.build(
      Lcom/google/common/cache/CacheLoader;)
        Lcom/google/common/cache/Cache;
   at debiki.QuotaManager.<init>(QuotaManager.scala:163) ~[classes/:na]

Guava 13 however requires JSR 305, or there's this weird error:
  [error] error while loading LocalCache, class file
   '.../guava-13.0.1.jar(com/google/common/cache/LocalCache.class)' is broken
  [error] (class java.lang.RuntimeException/bad constant pool tag 9 at byte 125)
  [warn] Class javax.annotation.CheckReturnValue not found -...

So add a dependency on JSR 305.

(A while ago, in commits e4d95088555 and b63f5828, from 2012-11-17, I
attempted to update to Guava 13, but that failed since I didn't google
for the correct phrases and didn't realize that JSR 305 is needed.)