Rename Scala templates to match new PageRole names
And fix odd compilation error: @tpi.body —> @tpi.bodyAndComments (why
didn't this cause errors earlier?).