Problems if upgrading to Nodejs 18 or Webdriver.io 8
Nodejs 18 error: See images/gulp/Dockerfile comment.

Webdriver.io 8 error:
  When running this: s/tyd e7 dir man --cd --da
  then the following step fails:

echo "tests/e2e-wdio7/specs/dir.manual.2br.e2e.ts" | tests/e2e-wdio7/node_modules/.bin/wdio tests/e2e-wdio7/wdio.conf.ts --cd --da --isInProjBaseDir --2browsers
Error: "ts-node/esm/transpile-only 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:399:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:846:13)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)

With:  node --version = v18.14.1