Upgrade to Bootstrap 3.1.1, stop using Bootstrap-Stylus
I cannot build Bootstrap-Stylus 3.1, because of unresolved NPM
dependencies:

Error: No compatible version found: grunt-contrib-stylus@'>=0.13.2- <0.14.0-'
ERR! fetch failed https://registry.npmjs.org/grunt-contrib-watch/-/grunt-contrib-watch-0.5.3.tgz

I don't want to troubleshoot this. The only cange I did to Bootstrap-Stylus
was in stylus/variables.styl:
---
-$screen-sm ?=                  768px;
+$screen-sm ?=                  540px; // was 768px originally, but that's far too wide
---

Don't remove modules/debiki-bootstrap yet though.