Upgrade to Scala 2.10.0-RC1, and newer version of Play
- Upgrade to newer Play 2.1-SNAPSHOT version 203df0e from 2012-10-28
  (commit message: 'fixing Concurrent.unicast'). Previous Play version
  was f7de038a48f1 from 2012-05-25 (also Play 2.1-SNAPSHOT).
- Remove SecureSocial dependency on play-plugins-util, which is
  available for Scala 2.9 only. (I copied a certain file from
  play-plugins-util to SecureSocial so it compiles anyway.)
- Place generated Rhino classes in target/scala-2.10.0-RC1/classes/ (not
  Scala-2.9.1)
- Use SBT version 0.12.1 (not 0.11.3)
- Add 'Typesafe Ivy Snapshots' repo, for Play SBT plugin
- Use Play Framework script located here:
  /mnt/data/dev/play/github2/play (not  but ) where I build Play 2.1.

However:
- Twitter Ostrich is not yet available for Scala 2.10, so there'll be an
  unresolved dependency error: com.twitter#ostrich_2.10;4.10.6: not
  found I suppose I'll have to stop using Ostrich for a while (I don't
  use it right now anyway actually).

(I've also changed to Scala 2.10.0-RC1 in submodules debiki-core,
-dao-pgsql and -tck-dao, and fixed two compilation errors.)