Remove @MirrorUsed, it breaks Javascript in Firefox
Apparently I haven't listed in `targets` all classes/things that I need to
list, so this error happens:
  TypeError: Cannot call method 'gMP' of undefined