Comment out unused code to avoid test suite compilation error
The compilation error is a compiler bug, the exact failure is:
[info] Compiling 5 Scala sources to [...]scala-2.9.1.final/test-classes...
[error] {file:/home/kajmagnus/me-dev/debiki/all/debiki-core/}default-
   ec2088/test:compile: java.lang.Error: no-symbol does not have owner
[error] Total time: 5 s, completed Feb 7, 2012 4:23:35 PM