Fix backup script bug: Use heredoc
There's this error: (every time insert_backup_log_row() is called)

   ... backup-script: Backing up config to: /var/opt/backups/talkyard/v1/archives/...-config.tar.gz ...
   ERROR:  syntax error at or near ":"
   LINE 4:         now_utc(), :'hostname', :'what', :'file_name', :'ran...

But with <<'EOF' it goes away.

Change to heredocs in Pg init.sh too, although has worked fine w/o.